# Generated by Django 3.2.7 on 2022-02-22 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('number', models.CharField(max_length=60, unique=True, verbose_name='student-ID/employee-ID')),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='user-type; 0=student; 1=teacher')),
                ('realname', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='user-real-name')),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, verbose_name='user-email')),
                ('init_ability', models.FloatField(null=True, verbose_name='初始化能力值')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.myclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
