# Generated by Django 3.2.7 on 2021-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='init_ability',
            field=models.FloatField(null=True, verbose_name='初始化能力值'),
        ),
    ]
