# Generated by Django 3.2.7 on 2021-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_init_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='user-email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='realname',
            field=models.CharField(max_length=100, null=True, verbose_name='user-real-name'),
        ),
    ]
