# Generated by Django 3.2.7 on 2022-01-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('users', '0005_myuser_joined_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='joined_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.myclass'),
        ),
    ]
