# myweb_uwsgi.ini file
[uwsgi]

# Django-related settings

socket = :8001

# the base directory (full path)
chdir = /home/test_system

# Django s wsgi file
module = test_system.wsgi:application

master = True

# maximum number of worker processes
processes = 4

chmod-socket    = 664

vacuum = True

home = /home/bsvenv/

stats = %(chdir)/uwsgi/uwsgi.status

pidfile = %(chdir)/uwsgi/uwsgi.pid

daemonize = /var/log/test-system-uwsgi.log

# max-requests = 5000