# Generated by Django 3.2.7 on 2022-02-22 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('is_subject', models.BooleanField()),
                ('total_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, unique=True)),
                ('correct', models.CharField(max_length=255)),
                ('discrimination', models.FloatField(default=1)),
                ('difficulty', models.FloatField()),
                ('guessing', models.FloatField(default=0)),
                ('exposure', models.FloatField(default=0)),
                ('option_A', models.CharField(max_length=255, null=True)),
                ('option_B', models.CharField(max_length=255, null=True)),
                ('option_C', models.CharField(max_length=255, null=True)),
                ('option_D', models.CharField(max_length=255, null=True)),
                ('knowledge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.knowledgepoints')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itembank.itemtype')),
            ],
        ),
    ]
