# Generated by Django 3.2.7 on 2021-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=20)),
                ('content', models.CharField(max_length=255, unique=True)),
                ('option_A', models.CharField(max_length=255)),
                ('option_B', models.CharField(max_length=255)),
                ('option_C', models.CharField(max_length=255)),
                ('option_D', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=30)),
                ('diffculty', models.FloatField()),
                ('discrimination', models.FloatField()),
                ('guessing', models.FloatField()),
            ],
        ),
    ]
