# Generated by Django 3.2.7 on 2022-03-16 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itembank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaperInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=100)),
                ('paper_ctime', models.DateField(auto_now_add=True)),
                ('paper_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testpaperinfo')),
            ],
        ),
    ]
