# Generated by Django 3.2.7 on 2021-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('content', models.CharField(max_length=255, unique=True)),
                ('correct', models.BooleanField()),
                ('discrimination', models.FloatField()),
                ('diffculty', models.FloatField()),
                ('guessing', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='choiceitems',
            name='type',
            field=models.IntegerField(),
        ),
    ]
