# Generated by Django 3.2.7 on 2022-03-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0002_testpaper_testpaperinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitems',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='correct',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='option_A',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='option_B',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='option_C',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='option_D',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_site', models.IntegerField(default=1, verbose_name='此图片用在题目的什么位置.默认：1=题干中；特殊：2=选择题的选项中')),
                ('img_url', models.ImageField(upload_to='images/')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='itembank.testitems')),
            ],
        ),
    ]
