# Generated by Django 3.2.7 on 2021-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0002_auto_20210910_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('content', models.CharField(max_length=255, unique=True)),
                ('correct', models.CharField(max_length=255)),
                ('discrimination', models.FloatField()),
                ('diffculty', models.FloatField()),
                ('guessing', models.FloatField()),
                ('option_A', models.CharField(max_length=255, null=True)),
                ('option_B', models.CharField(max_length=255, null=True)),
                ('option_C', models.CharField(max_length=255, null=True)),
                ('option_D', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChoiceItems',
        ),
        migrations.DeleteModel(
            name='TFItems',
        ),
    ]
