# Generated by Django 3.2.7 on 2021-10-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0003_auto_20210912_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testitems',
            old_name='diffculty',
            new_name='difficulty',
        ),
    ]
