# Generated by Django 3.2.7 on 2022-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0004_rename_diffculty_testitems_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
