# Generated by Django 3.2.7 on 2022-01-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0005_knowledgepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitems',
            name='knowledge_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itembank.knowledgepoints'),
        ),
    ]
