# Generated by Django 3.2.7 on 2022-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0006_testitems_knowledge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitems',
            name='exposure',
            field=models.FloatField(default=0),
        ),
    ]
