# Generated by Django 3.2.7 on 2022-01-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0007_testitems_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitems',
            name='discrimination',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='guessing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testitems',
            name='knowledge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.knowledgepoints'),
        ),
    ]
