# Generated by Django 3.2.7 on 2021-09-12 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='考试开始时间')),
                ('end_time', models.TimeField(auto_now=True, null=True, verbose_name='考试结束时间')),
                ('total_time', models.DurationField(null=True, verbose_name='总考试用时')),
                ('newest_ability', models.FloatField(null=True, verbose_name='做题过程中最新的能力值评估')),
                ('final_ability', models.CharField(max_length=100, null=True, verbose_name='最终能力估计')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
