# Generated by Django 3.2.7 on 2022-02-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itembank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(verbose_name='考试开始时间')),
                ('end_time', models.DateTimeField(default=None, null=True, verbose_name='考试结束时间')),
                ('total_time', models.DurationField(null=True, verbose_name='总考试用时')),
                ('newest_ability', models.FloatField(null=True, verbose_name='做题过程中最新的能力值评估')),
                ('final_ability', models.CharField(max_length=100, null=True, verbose_name='最终能力估计')),
                ('finish_object_test', models.BooleanField(null=True, verbose_name='是否完成客观题测试')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='学生的回答')),
                ('score', models.FloatField(null=True, verbose_name='得分')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='学生的回答')),
                ('judge', models.BooleanField(verbose_name='是否正确')),
                ('process_ability', models.FloatField(verbose_name='做完此题后的能力评估')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InitTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='学生的回答')),
                ('judge', models.BooleanField(verbose_name='是否正确')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testinfo')),
            ],
        ),
    ]
