# Generated by Django 3.2.7 on 2022-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='final_ability',
            field=models.FloatField(max_length=100, null=True, verbose_name='最终能力估计'),
        ),
    ]
