# Generated by Django 3.2.7 on 2021-09-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0003_auto_20210912_1531'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='学生的回答')),
                ('judge', models.BooleanField(verbose_name='是否正确')),
                ('process_ability', models.FloatField(verbose_name='做完此题后的能力评估')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InitTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='学生的回答')),
                ('judge', models.BooleanField(verbose_name='是否正确')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testinfo')),
            ],
        ),
    ]
