# Generated by Django 3.2.7 on 2021-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_inittestprocess_objecttestprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='end_time',
            field=models.TimeField(default=None, null=True, verbose_name='考试结束时间'),
        ),
    ]
