# Generated by Django 3.2.7 on 2022-03-26 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_testinfo_final_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_total', models.IntegerField(default=28, validators=[django.core.validators.MinValueValidator(0)], verbose_name='选择题数目')),
                ('judge_total', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='判断题数目')),
                ('glossary_total', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='名词解释数目')),
                ('saqs_total', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='简答题数目')),
                ('discuss_total', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='论述题数目')),
            ],
            options={
                'unique_together': {('choice_total', 'judge_total', 'glossary_total', 'saqs_total', 'discuss_total')},
            },
        ),
        migrations.AddField(
            model_name='testinfo',
            name='test_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testsetting'),
        ),
    ]
