# Generated by Django 3.2.7 on 2021-12-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_testinfo_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='考试结束时间'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='考试开始时间'),
        ),
    ]
