# Generated by Django 3.2.7 on 2022-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20211227_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='start_time',
            field=models.DateTimeField(verbose_name='考试开始时间'),
        ),
    ]
