# Generated by Django 3.2.7 on 2022-02-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0009_itemtype'),
        ('testing', '0005_alter_testinfo_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTestProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='学生的回答')),
                ('score', models.FloatField(verbose_name='得分')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.testitems')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testinfo')),
            ],
        ),
    ]
