# Generated by Django 3.2.7 on 2022-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_subjecttestprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='finish_object_test',
            field=models.BooleanField(null=True, verbose_name='是否完成客观题测试'),
        ),
        migrations.AlterField(
            model_name='subjecttestprocess',
            name='score',
            field=models.FloatField(null=True, verbose_name='得分'),
        ),
    ]
